---
on:
  - push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Cache OCaml
        id: cache-ocaml
        uses: actions/cache@v2
        with:
          path: ~/.opam
          key: ${{ runner.os }}-ocaml
      - name: Set up OCaml
        if: steps.cache-ocaml.outputs.cache-hit != true
        uses: ocaml/setup-ocaml@v1.1.11
      - run: opam install . --deps-only --with-test
      - run: opam exec -- dune build
      - name: Cache Build
        id: cache-build
        uses: actions/cache@v2
        with:
          path: ~/_build
          key: ${{ runner.os }}-build

  test:
    runs-on: ubuntu-latest
    needs:
      - build
    steps:
      - name: Restore OCaml
        id: restore-ocaml
        uses: actions/cache@v2
        with:
          path: ~/.opam
          key: ${{ runner.os }}-ocaml
      - name: Restore Build
        id: restore-build
        uses: actions/cache@v2
        with:
          path: ~/_build
          key: ${{ runner.os }}-build
      - run: opam exec -- dune runtest
